numberscope/frontscope

- package-lock.json
> Trying to move serialize-js to 3.1

- package-lock.json
- src/sequences/OEISSequenceTemplate.ts
> fix: Allow OEIS sequences to work without a modulus

- src/views/ToolMain.vue
> feat: automatically activate a sequence when added

- src/sequences/SequenceCached.ts
- src/sequences/SequenceRandom.ts
> feat(Sequences): add random sequence generator

- src/sequences/OEISSequenceTemplate.ts
Changes the route to backend used to obtain OEIS sequence values to one
that includes the original OEIS index information based on the offset.
Sets the first and last indices of the resulting Sequence object to
match the data from the OEIS.
Also strengthens the error checking on the modulo and numElements parameters
of the OEISSequenceTemplate.
Resolves #20.
Resolves #70.
> fix(OEISSequenceTemplate): respect OEIS offset

- .eslintrc.cjs
- src/sequences/OEISSequenceTemplate.ts
- src/sequences/SequenceCached.ts
- src/sequences/SequenceClassDefault.ts
- src/sequences/SequenceFormula.ts
- src/sequences/SequenceInterface.ts
- src/visualizers/VisualizerShowFactors.ts
Also adds implementations for SequenceFormula for sequence values up to
at least one million, and for OEISSequenceTemplate for factorizations
provided by backscope.
As an illustration of the facility, adds a simple "ShowFactors" visualizer.
Resolves #116.
> feat(SequenceInterface): add getFactors() method for factorizations

- .env
- .prettierignore
- doc/onboarding.md
- doc/running-from-source.md
- doc/submitting-pull-requests.md
- src/sequences/OEISSequenceTemplate.ts
This PR combines https://github.com/numberscope/frontscope/pull/148 and https://github.com/numberscope/frontscope/pull/158.
Here are the items from https://github.com/numberscope/frontscope/pull/148#issuecomment-1262606746 that are addressed in this PR:
> Add onboarding doc, change code and docs related to server URL

- doc/pull-request-checklist.md
Since it is easy to miss in the "working with Git" document,
which experts may not read anyway, but we would expect
everyone making a PR to read the PR checklist.
> doc(Pull Requests): Add the snake_case requirement

- mkdocs.yml
- requirements.txt
By submitting this PR, I am indicating to the Numberscope maintainers that I
have read and understood the
[contributing guidelines](https://numberscope.colorado.edu/doc/CONTRIBUTING/)
and that this PR follows those guidelines to the best of my knowledge. I have
also read the
[pull request checklist](https://numberscope.colorado.edu/doc/doc/pull-request-checklist/)
and followed the instructions therein.
<hr/>
Keeps us in sync with current versions of the mkdocs ecosystem.
Also, these latest versions are a bit more explicit about what files are or are not processed. This should make docsite problems like the ones encountered with #178 easier to understand and track down.
P.S. Remember to `npm install` if you check out this branch to test it.
> chore: Update mkdocs-semiliterate to v0.7.0

- .github/dependabot.yml
<hr/>
Basically the title. Adds configuration for Dependabot. Note that I have it configured to run weekly, which we might want to change to daily. Resolves https://github.com/numberscope/frontscope/issues/24.
> feat: add Dependabot YAML file

- doc/onboarding.md
<hr/>
Don't recommend/approve a specific editor for use with Numberscope. Keep note that VS Code works well with Vue.
> docs(onboarding): don't recommend editor

- doc/husky-pre-commit.md
- doc/running-from-source.md
- mkdocs.yml
<hr/>
Resolves https://github.com/numberscope/frontscope/issues/155.
> doc: Small fixes to running-from-source

- package-lock.json
- package.json
> chore: bump p5 to 1.9.2 and @types/p5 to 1.7.6

- requirements.txt
Per https://github.com/numberscope/frontscope/security/dependabot/52
Since this isn't really mainly a python project, we're not setup
for dependabot to generate python updates itself.
As this is a security issue, felt best to do a manual update now.
Note this can only affect documentation generation.
<hr/>
> chore: Update pymdown-extensions

- doc/about.md
<hr/>
Just trying to get the about page up-to-date with new folks coming in.
> doc: Update contributors and current leadership of project

- src/App.vue
- src/components/SpecimenBar.vue
- src/components/Tab.vue
- src/shared/browserCaching.ts
- src/views/Gallery.vue
- src/views/Scope.vue
- src/views/minor/NavBar.vue
- src/visualizers/P5Visualizer.ts
- src/visualizers/VisualizerInterface.ts
<hr/>
Navbar
* Removes the navbar from App.vue. The navbar now has to be added
to each view separately because it may be different for differrent views.
* Makes the navbar taller and adds a slot to accommodate the specimen bar.
Specimen bar
* Adds the specimen bar with replay, pause/resume, share, and save buttons.
Visualizers
* Adds a continue function to be executed by the resume button. …
> Specimen bar [cleaned]

- doc/about.md
<hr/>
Two columns in contributor list.
Resolves #314.
> doc: Reformat contributor list per #314.

- src/shared/browserCaching.ts
- src/shared/defineFeatured.ts
> fix: Don't let one randomly selected featured specimen replace another

- src/sequences/Formula.ts
- src/shared/ParamType.ts
> fix[Formula]: reject unknown function at parse to avoid throwing error

- src/components/ParamEditor.vue
- src/components/SpecimensGallery.vue
- src/components/Thumbnail.vue
- src/main.ts
* Lines of the list form of SpecimensGallery components (sequence switcher, gallery, etc.)
* The sequence name and visualizer name in a parameter tab (since they bring up the switcher modals).
Resolves #513.
<hr/>
> ui: More "finger pointer" cursors to indicate interactions.

- doc/about.md
- src/visualizers/Grid.ts
> feat: Correct name of contributor

- src/views/minor/NavBar.vue
<hr/>
Not much else to say; this is a pretty minor change.
Resolves #535.
> feat: Can click directly on navbar 'Help' to go to docs

- src/visualizers-workbench/ShiftCompare.ts
<hr/>
About the smallest/shortest PR ever. Resolves the alpha portion of #429.
> refactor: Move ShiftCompare to workbench
