numberscope/frontscope

src/components/BundleManager.vue
src/components/CanvasArea.vue
src/components/VizualizationMenu.vue
src/components/bundleCard.vue
src/sequences/sequenceClassDefault.ts
src/sequences/sequenceConstant.ts
src/views/ToolMain.vue
src/vizualizers/vizualizerDefault.ts
src/vizualizers/vizualizerDifferences.ts
src/vizualizers/vizualizerInterface.ts
src/vizualizers/vizualizerModFill.ts
src/vizualizers/vizualizerShiftCompare.ts
src/vizualizers/vizualizerTurtle.ts
todo.md

Merging in a full size canvas area

Efficient viz

---

src/visualizers/VisualizerDifferences.ts

The problem was that VisualizerDifferences was requesting far too many
terms from the sequence, and so ran into trouble when there weren't more
terms available (say if you hadn't loaded that many from the OEIS) and the
unhandled errors terminated the operation of the visualizer.
There is an underlying issue, however, that there is not a graceful
convention for handling unavailable values in a sequence; that deserves
a separate issue.
Resolves #17.

fix: Allow VisualizerDifferences to work with OEIS sequences

---

src/components/SeqGetter.vue
src/components/SeqSelector.vue
src/components/SeqVizParamsModal.vue
src/components/SequenceMenu.vue
src/sequences/OEISSequenceTemplate.ts
src/sequences/SequenceConstant.ts
src/sequences/SequenceFormula.ts
src/sequences/SequenceInterface.ts
src/sequences/SequenceNaturals.ts
src/views/ToolMain.vue

This code is a step toward resolving #23 and does not add new functionality. 
Rather, it makes explicit the fact that there are three kinds of Sequence items:
Sequence "Getter"s that have a button at the bottom of the sequence menu,
which when used produces a new button for the specific sequence created;
Sequence "Family"s that have a button in the top of the sequence menu, but
need parameters to create a specific sequence each time their button is
pressed; and Sequence "Instance"s that were created by a "Getter" and which
select that one specific sequence when their button is pressed.
Formerly, which one of these kinds a Sequence functioned as was an indirect
result of whether it had a SequenceExportModule and whether or not "isOeis"
was true in that module; also, the button for the only …

refactor: Delineate three kinds of Sequence items

---

src/sequences/SequenceFormula.ts

fix(SequenceFormula): Allow formulas whose parse tree has only one node

---

src/sequences/OEISSequenceTemplate.ts
src/sequences/SequenceCached.ts
src/sequences/SequenceClassDefault.ts
src/sequences/SequenceConstant.ts
src/sequences/SequenceFormula.ts
src/sequences/SequenceInterface.ts
src/sequences/SequenceNaturals.ts
src/sequences/SequenceRandom.ts
src/visualizers/VisualizerDifferences.ts
src/visualizers/VisualizerModFill.ts
src/visualizers/VisualizerShiftCompare.ts
src/visualizers/VisualizerTurtle.ts

[EDIT: This is now the agreed-upon resolution of #42, so this IS NOW advanced for review. Thanks!]
To support this, SequenceInterface now has properties first and last
giving the smallest and largest valid indices (with last allowed to
be infinity). That way, it never has to return undefined.
Resolves #42.
Resolves #19.
[Everything below here is now obsolete.]
NOTE: this is presented as a reference implementation for comparison with #50 of the alternate plan for dealing with Sequence return types and computing with Sequence values, as in the discussion for issue #48. Please see that discussion and comment.
This had not been suggested for review until further commentary/consensus has been reached in #48 as to which direction to go at this point. I just thought it might be helpful to see …

refactor: Sequence getElement consistently returns BigInt

---

package.json
public/index.html

We rename the title from "newnumberscope" to "Numberscope". The old
title was obtained from the "name" field in `package.json`. I'm not a
fan of this method since the "name" field in `package.json` is supposed
to be lowercase. Thus, we change the "name" in `package.json` to be
"frontscope" to match the repo's name.
Related to https://github.com/numberscope/frontscope/pull/88 in that
it's a minor cosmetic thing that will make the frontend look a bit
nicer.
Here's how the title should look now:

chore: Rename Title

---

.eslintrc.js
.prettierignore
.prettierrc.json
doc/formatting-code.md
package-lock.json
package.json
tools/editor/autoformat.el

Install and configure the Prettier code formatter. We also install the
eslint-config-prettier package to get ESLint and Prettier to play nicely
together, as recommended by the Prettier docs.
For
https://github.com/numberscope/frontscope/issues/26.
Related to https://github.com/numberscope/frontscope/issues/69.
Prettier is working for me in Visual Studio Code. I also use Neovim and Emacs, so if either @katestange or @gwhitney need help setting up Prettier, I might be able to help. (I've used most of the popular Vim/Neovim plugin managers, but I've only used [use-package](https://github.com/jwiegley/use-package) for Emacs.)
As for actually formatting the files, it can be done in one fell swoop, but I think I'll format each file individually and make sure nothing breaks as they are …

chore: Add Code Formatter

---

package-lock.json
src/views/minor/Footer.vue
tests/unit/Footer.spec.ts

https://github.com/numberscope/frontscope/pull/101 made the footer
disappear. In this commit, we make it reappear. We also make it dynamic
so that it doesn't become outdated. We also add a test for the footer.
I tried to add this commit in
https://github.com/numberscope/frontscope/pull/101, but I must have
merged it incorrectly.

fix: Make Footer Reappear, Make Footer Dynamic

---

.eslintrc.cjs
.husky/pre-commit
.prettierignore
README.md
package-lock.json
package.json

It turns out that prettier-eslint suppresses eslint errors that cannot
be fixed (as it is focused just on fixing the things it can), and that
files changed in pre-commit hooks are not automatically staged.
Together, these issues were allowing files with prettier discrepancies
and/or eslint errors to be committed.
This PR fixes the situation by (a) installing and using `lint-staged`
to overcome the second difficulty, and (b) explicitly running a new
`lint:check` script after the prettier-eslint step to prevent eslint errors
from getting through.
For better infomation to the committer, it also adds a `lint:list` script
that just lists files that are out of prettier-eslint compliance, and
documents all of the new scripts in the README.
Finally, it promotes unused variables to an error so …

style: Don't allow files with prettier/eslint errors to be commited

---

.eslintrc.cjs
.husky/pre-commit
package.json
src/components/BundleCard.vue
src/components/BundleManager.vue
src/components/CanvasArea.vue
src/components/SeqGetter.vue
src/components/SeqSelector.vue
src/components/SeqVizParamsModal.vue
src/components/SequenceMenu.vue
src/components/StopDrawingButton.vue
src/components/ToolSelector.vue
src/components/VisualizationMenu.vue
src/components/__tests__/SeqSelector.spec.ts
src/sequences/OEISSequenceTemplate.ts
src/sequences/SequenceFormula.ts
src/shared/Paramable.ts
src/views/About.vue
src/views/Help.vue
src/views/Scope.vue
src/views/UserManual.vue
src/visualizers/VisualizerChaos.ts
src/visualizers/VisualizerShiftCompare.ts

This PR modifies the node `dev` and `build` scripts and the pre-commit
actions to typecheck all code in Vue components. Correspondingly, it
adjusts all of the components to pass TypeScript type checking. In particular,
this means boilerplate of a call to Vue.defineComponent() in every component
and view (per Vue 3 documentation; otherwise TypeScript cannot infer the
proper types).
The most significant resulting change was to the mechanism of generating
unique canvas ids in BundleCard, as the previous mechanism did not allow
defineComponent() to infer the type of the `cid` member. This commit
therefore switches to a later proposed mechanism in the same Vue GitHub issue
referenced by the comment on the previous mechanism.
One other change worth mentioning is that in several places data …

chore: Adjust vue components to type correctly

---

mkdocs.yml
package.json
tools/pyrun.mjs

Adds a helper Node script in tools which examines the platform and
spawns the appropriate command to run the specified program in the
virtual environment set up in this project on install.
Resolves #149.

fix: Run python tools properly from Windows

---

package.json

Fixes https://github.com/numberscope/frontscope/issues/182.

fix: use `python -m` in `postinstall` script

---

.github/pull_request_template.md

By submitting this PR, I am indicating to the Numberscope maintainers that I
have read and understood the
[contributing guidelines](https://numberscope.colorado.edu/doc/CONTRIBUTING/)
and that this PR follows those guidelines to the best of my knowledge. I have
also read the
[pull request checklist](https://numberscope.colorado.edu/doc/doc/pull-request-checklist/)
and followed the instructions therein.
<hr/>
GitHub seems to respect newlines in markdown, so when the PR template is rendered, it looks strange. (See above.) This PR puts the initial paragraph in the PR on one line so that it renders properly on GitHub.

fix(PR template): put paragraph on one line

---

doc/pull-request-checklist.md

<hr/>
This PR adds notes to the PR checklist. One is about limiting your PR's focus to one thing. The other encourages small, incremental PRs rather than monolithic PRs.

docs: limit PR focus, make PRs small

---

src/components/BundleCard.vue
src/components/SequenceMenu.vue
src/views/Scope.vue
src/visualizers/VisualizerShiftCompare.ts

<hr/>
This PR removes all instances of `console.log()`. Resolves https://github.com/numberscope/frontscope/issues/45.

refactor: remove all `console.log()` instances

---

doc/pull-request-checklist.md

<hr/>
Adds notes about optionally updating the list of contributors at the end of your PR review.

docs(PR checklist): reviewer updates contributors

---

src/components/BundleCard.vue
src/components/CanvasArea.vue
src/sequences/Cached.ts
src/sequences/OEIS.ts

<hr/>
Before this PR, all cached sequences loaded factorizations into the cache in strict lockstep with values. But many visualizers do not use the factorizations, and they require extra computations and/or http requests that can be wasteful if the results will not be used. This PR decouples the two caches, so that values can be cached without factorizations (although not vice versa, since …

fix: Reduce error alerts by increasing caching tolerance

---

src/visualizers/Histogram.ts

<hr/>
This PR is an improved version of #228 which will be closed in favour of this one.  This is a rebased version of that PR (i.e. cherry-picked the commits from that PR), with improvements to code and removal of bugs (at the level expected if I had reviewed the PR myself).  Besides some cleaning up of documentation, and some slight tweaking of visual spacing to allow for text, the scope …

Histogram Factors Visualizer: enhancement: mouseover and y-axis

---

doc/server-administration.md

doc: Start a page concerning server administration

---

src/components/BundleCard.vue
src/components/CanvasArea.vue
src/visualizers/P5Visualizer.ts
src/visualizers/VisualizerInterface.ts

Refactors the VisualizerInterface to require matching inhabit() and
depart() calls, both taking an HTMLElement where its view will reside.
A second inhabit() before any depart() automatically calls depart()
on the prior view.
Resolves #295.

fix: Tolerate visualizer inhabit()ing a new div before removal from old

---

src/components/BundleCard.vue
src/visualizers/Chaos.ts
src/visualizers/Differences.ts
src/visualizers/Grid.ts
src/visualizers/Histogram.ts
src/visualizers/ModFill.ts
src/visualizers/NumberGlyph.ts
src/visualizers/P5Visualizer.ts
src/visualizers/ShiftCompare.ts
src/visualizers/ShowFactors.ts
src/visualizers/Turtle.ts
src/visualizers/VisualizerInterface.ts

Three related interface changes for the Visualizer hierarchy, as
discussed in #293. These are all designed to make some of the
details of defining a Visualizer less confusing and more concise.
(A) In P5Visualizer, draw() should be abstract and hence required
on runnable derived Visualizers, since any (additional) boilerplate
needed by all P5Visualizers would go in the function that wraps
this method in the default inhabit() method. Thus implementation
draw() functions no longer need to call super.draw().
(B) Since setup() is the default p5 initialization method and can only
be called once per sketch anyway, clarify that generally initialization
should be carried out in setup() rather than inhabit(), in derived
Visualizers.
(C) Since `name` is used as an instance property in …

refactor: Improve uniformity of VisualizerInterface and P5Visualizer

---

CONTRIBUTING.md
doc/gitting-it-right.md
doc/making-a-visualizer.md
doc/working-with-git-and-github.md
src/visualizers-workbench/P5VisualizerTemplate.ts

<hr/>
Over a number of commits, numerous missing and broken links in the
MkDocs documentation for Numberscope had accumulated. This PR restores
all MkDocs links to working order, including re-creating a section
on submitting a pull request that had somehow been lost altogether in
a previous documentation refactor.
When this commit is checked out, `npm run doc:serve` should not issue
any …

doc: Restore broken and missing links 

---

src/shared/__tests__/browserCaching.spec.ts
src/shared/browserCaching.ts

<hr/>
This PR is second in the PR merge chain.
Specimen browser storage
This PR adds two new files that aren't used anywhere at this point: browserCaching.spec.ts and browserCaching.ts. browserCaching.ts adds the interface for storing specimens in the browser. This file is updated in later iterations, but largely remains the same.
[Maintainer's note: we would not usually allow a PR that …

Specimen browser storage [cleaned]

---

index.html
package-lock.json
package.json
src/App.vue
src/components/Tab.vue
src/shared/Specimen.ts
src/views/Gallery.vue
src/views/Scope.vue
src/views/__tests__/Gallery.spec.ts
src/visualizers/P5Visualizer.ts
src/visualizers/VisualizerInterface.ts

<hr/>
Changes to tabs
* Added buttons that let you control the tabs without dragging
* Support minimizing of tabs.
* Added a highlight to the tab that is currently selected.
* Initial mobile compatibility in the style section of Tab.vue
Resizing
* Added a reset function to a specimen. This is a hard reset that is used
when the specimen is resized and it doesn't override resized function.
* …

Resizing and url integration [cleaned]

---

src/views/Scope.vue

<hr/>
Fixes the reversion in #368: as a tab is dragged, the left dropzones again highlight as the tab enters the region in which the tab will dock into the zone.
Resolves #376.

Fix dropzone [ui2]

---

.eslintrc.cjs
src/App.vue
src/assets/scss/_variables.scss
src/components/MageExchangeA.vue
src/components/ParamEditor.vue
src/components/ParamField.vue
src/components/SpecimenBar.vue
src/components/SpecimenCard.vue
src/components/SpecimensGallery.vue
src/components/SwitcherModal.vue
src/components/Tab.vue
src/shared/Paramable.ts
src/shared/Specimen.ts
src/shared/layoutUtilities.ts
src/views/Gallery.vue
src/views/Scope.vue
src/views/minor/NavBar.vue
src/visualizers/Chaos.ts
src/visualizers/Differences.ts
src/visualizers/Histogram.ts
src/visualizers/P5Visualizer.ts
src/visualizers/Turtle.ts
src/visualizers/VisualizerInterface.ts
vite.config.ts

<hr/>
Switchers
* Adds a new button on each tab to change the sequence/visualizer. It is still not possible to switch to an OEIS sequence (that's added in the next PR in the sequence, but changing to all other sequences/visualizers should work, provided they work themselves.
Parameter Editor
* Updates the param editors to work with switching visualizers and specimens.
* More specifically, …

Sequence and visualizer switcher [cleaned]

---

src/components/SpecimenCard.vue
src/components/SpecimensGallery.vue
src/components/SwitcherModal.vue
src/sequences/sequences.ts
src/shared/__tests__/browserCaching.spec.ts
src/shared/browserCaching.ts
src/shared/defineFeatured.ts
src/views/Gallery.vue

<hr/>
This PR represents another cleaned portion of the seventh Delft PR (#360). It allows OEIS sequence cards to be added and deleted from the list that is shown in the sequence switcher. It stores this list of "active" OEIS IDs in browser localStorage so that it is persistent across page reloads, tab closures, and the like. This PR still has a completely non-functional OEIS Search bar; …

feat: Allow adding and dropping of OEIS sequence cards

---

CONTRIBUTING.md
doc/gitting-it-right.md
doc/making-a-visualizer.md
doc/onboarding.md
doc/pull-request-checklist.md
doc/running-from-source.md
doc/visual-studio-code-setup.md
doc/working-with-git-and-github.md

<hr/>
Resolves https://github.com/numberscope/frontscope/issues/221.
There is still a signifcant amount of repetition/overlap among
CONTRIBUTING.md, and in the doc/ directory, onboarding.md,
running-from-source.md, and working-with-git-and-github.md. I wasn't
sure how we might compartmentalize these, because they are at
different levels of detail and for different audiences.
Since they are …

doc: Harmonize guidance on git, cloning, and other workflows.

---

e2e/tests/featured.spec.ts
e2e/tests/gallery.spec.ts
e2e/tests/idiot.spec.ts
e2e/tests/scope.spec.ts
e2e/tests/stress.spec.ts
e2e/tests/transversal.spec.ts
src/components/SwitcherModal.vue
src/shared/Paramable.ts
src/shared/Specimen.ts
src/shared/browserCaching.ts
src/shared/defineFeatured.ts
src/shared/specimenEncoding.ts

<hr/>
Resolves #426.
Note that specimenQuery() and parseSpecimenQuery() had to move out of src/shared/browserCaching.ts to their own new file, to avoid circular inclusions.

feat: Default to a featured visualization (not Random ModFill)

---

src/components/ParamField.vue
src/visualizers/Turtle.ts

<hr/>
Resolves #432.
Also includes last two Turtle parameters into its user guide page, that accidentally got left out of #404.

ui: Move parameter descriptions just below their entry boxes

---

e2e/tests/scope.spec.ts
src/App.vue
src/components/SpecimenCard.vue
src/components/SpecimensGallery.vue
src/components/SwitcherModal.vue
src/components/Tab.vue
src/components/Thumbnail.vue
src/router/index.ts
src/shared/Specimen.ts
src/shared/__tests__/specimen.spec.ts
src/shared/math.ts
src/views/Scope.vue
src/visualizers/Differences.ts

Prior to this change, the browser 'back' button would always update the
URL, but the visualization would typically not change if you were going
from one scope URL (`/?name=Blah&...`) to another.
This PR remedies the situation by watching for route changes in the
Scope view, and reloading the new visualizer and sequence **into** the
specimen already being viewed. Implementing this tactic requires the
ability to completely change the sequence and visualizer of a specimen,
which previously did not exist.
The change also enables delaying specimen initialization from Vue setup()
time to just before the component is mounted. As a result, the Vue setup
is not asynchronous, so the experimental Vue `<Suspense>` tag is no longer
needed.
Adds a test that the back button actually took effect, to the …

fix: Ensure back button updates visualization

---

src/sequences/__tests__/simpleFactor.spec.ts
src/sequences/simpleFactor.ts

<hr/>
Resolves those portions of #475 that can be dealt with before upgrading to mathjs 13 and bigint within Formulas.
That issue #475 will need to be revised and adjusted to beta milestone once this PR is merged.
Also adds at least rudimentary tests for simpleFactor, including one that won't pass until we make it less "simple".

fix: Don't attempt to factor 'unsafe' integers

---

src/components/SwitcherModal.vue

fix: Don't stretch SpecimenCards when only one row

---

src/components/Tab.vue
src/sequences/Formula.ts
src/views/Scope.vue

<hr/>
Prior to this PR, dragging a tab on top of a docked one would leave
it floating over the docked tab. Moreover, if the empty zone in the
sidebar was less than half the size of the tab being dragged, it would
be impossible to dock the dragged tab at all.
Now any drag into a sidebar with at least one empty zone results in
a docking to the targeted zone if it is empty, or the first empty …

fix: Drag into sidebar always docks into an empty zone

---

e2e/tests/scope.spec.ts
src/components/Thumbnail.vue
src/components/thumbnails.ts
src/visualizers/P5GLVisualizer.ts
src/visualizers/P5Visualizer.ts
src/visualizers/VisualizerInterface.ts

<hr/>
Resolves #506.
Also adds a method to the VisualizerInterface that indicates whether the visualizer uses WebGL. This could/should probably be used in testing to determine which tests use WebGL rather than checking the name of the visualizer, but that would be a different PR.
Also makes a baby step toward trying to understand the sporadic failures of the "minimizing a tab" e2e test in …

feat: Limit WebGL contexts in use by replacing thumbnails with snapshots when done

---

src/sequences/OEIS.ts
src/shared/__tests__/layoutUtilities.spec.ts
src/shared/layoutUtilities.ts

<hr/>
This PR provides a utility for converting large bigints to strings that include thin spaces every three characters so that they can linebreak in paragraphs, etc (and they are more readable that way anyway). Currently, such numbers were only creating a problem in the OEIS sequence modulus, so that's the only place the facility is used; we could apply it more generally in the future if …

fix: linebreak long numbers (in sequence mod)

---

src/visualizers/FactorFence.ts
src/visualizers/P5Visualizer.ts

<hr/>
Resolves #478.
I can't get anything bad to happen with these code changes, but please beat on FactorFence as thoroughly as you can when reviewing. Thanks!

fix: prevent FactorFence key controls from firing when an input is focused
